ing1 = input("Enter ingredient 1")
am1 = input("Ounces of "+ing1 + ":")
ing2 = input("Enter ingredient 2")
am2 = input("Ounces of "+ing2 + ":")
ing3= input("Enter ingredient 3")
am3 = input("Ounces of "+ing3 + ":")
numOfServings=input("Number of servings:")
print("Total ounces of "+ing1 + ":" + str(int(numOfServings)int(am1)))
print("Total ounces of "+ing2 + ":" + str(int(numOfServings)int(am2)))
print("Total ounces of "+ing3 + ":" + str(int(numOfServings)*int(am3)))